name: hello-world
on:
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pkg
        id: pkg
        uses: buildooor/ghaction@dc9a087f45e6e4fda553ba8658c74f2b8f4eaff7
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          rpc-url: ${{ secrets.RPC_URL }}
          network: sepolia
          branch: master
          on-pull-request-merged: true