name: hello-world
on:
  pull_request:
    types: [closed]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pkg
        id: pkg
        uses: buildooor/ghaction@1c1bcbabe97bd24fde3f8739bd069ea6b803d2dd
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          rpc-url: ${{ secrets.RPC_URL }}
          network: sepolia
          branch: master