name: hello-world
on:
  push:
  pull_request:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pkg
        id: pkg
        uses: buildooor/ghaction@43e5dedda48ee5b926d9f9295f69c23131d040e6
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          rpc-url: ${{ secrets.RPC_URL }}
          network: sepolia
          branch: master